<?php

if(! defined('ABSPATH')) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	exit();
}

?>

<div>
    <h3><?php echo __('Import Wallets', 'fsww'); ?></h3>
	<form method="post" action="<?php echo admin_url('admin-ajax.php') ?>" enctype="multipart/form-data">
		
		<input type="hidden" name="action" value="fsww_import">
		
		<div class="input-box">
			<p class="tip"><?php echo __('CSV file generated by the plugin in the export page', 'fsww'); ?></p>
			<div class="label">
				<span><?php echo __('CSV File', 'fsww'); ?></span>
			</div>
			<div class="input">
				<input class="input-field" name="fsww_source_file" type="file" accept=".csv">
			</div>
		</div>
		
		<p class="submit mb">
			<input name="save" class="button button-primary" value="<?php echo __('Import', 'fsww'); ?>" type="submit">
			<br class="clear">
		</p>
	</form>
</div>
